### PR TITLE
[[fix]] remove line readme

### PR DESCRIPTION
**Pull request by SergioPadilla**

### CODE REVIEW

**Comment by contint** [comment]
Can one of the admins verify this patch?

**Review by epgtid — APPROVED** [review]

**Review by epgtid — APPROVED** [review]
test hook

**Review by epgtid — DISMISSED** [review]
another test

**Comment by epgtid** [comment]
test comment

**Comment by epgtid** [comment]
run ci

**Comment by epgtid** [comment]
run ci

**Comment by epgtid** [comment]
run ci

**Pull request closed without merging**
